openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /user/settings:
    get:
      description: "Основные настройки пользователя"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSettingsResponse"
components:
  schemas:
    UserSettingsResponse:
      type: "object"
      required:
        - name
        - age
        - gender
        - mentalEnergyLevel
      properties:
        name:
          type: "string"
          example: "Иван"
        age:
          type: "integer"
          example: 29
        gender:
          type: "string"
          example: "male"
        mentalEnergyLevel:
          type: "integer"
          minimum: 1
          maximum: 10
          example: 7
